spring:
  datasource:
    url: jdbc:mysql://localhost:3306/railway?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=True
    username: root
    password: Asuna7878
    hikari:
      maximum-pool-size: 10
      connection-timeout: 60000
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          fetch_size: '50'
          batch_size: '50'
    hibernate:
      ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

springdoc:
  api-docs:
    path: /api/v1/api-docs
  swagger-ui:
    path: /api/v1/swagger-ui.html

app:
  jwtExpirationInMs: '604800000'
  jwtSecret: JWTSuperSecretKey

server:
  port: 8080

